version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
  
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
    ports:
       # AMQP protocol port
       - '5672:5672'
       # HTTP management UI
       - '15672:15672'

  mvpnode:
    image: node:18.1.0
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: sh -c "cd /app && npm install && npm run start:dev"
    depends_on:
      - rabbitmq3
      - mongodb_container

volumes:
  mongodb_data_container:
